services:
  pg:
    container_name: 'postgres-motoxpress'
    image: postgres:latest
    environment: 
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=2007
      - POSTGRES_DB=motoxpress
    ports:
      - '5433:5432'
    volumes:
      - pg-data:/var/lib/postgresql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pg-data:

